run_name: whisper_large_v3_lora_all
model:
  name: openai/whisper-large-v3
data:
  dataset_dir: data/processed
  languages: null
lora:
  enabled: true
  r: 16
  lora_alpha: 32
  target_modules:
    - q_proj
    - v_proj
  lora_dropout: 0.05
  bias: none
evaluation:
  normalization: starter_lower
tracking:
  report_to: none
  local_dir: outputs/experiments
training_args:
  output_dir: checkpoints/whisper_large_v3_lora_all
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 16
  learning_rate: 1.0e-4
  warmup_steps: 100
  max_steps: 1500
  gradient_checkpointing: true
  fp16: true
  eval_strategy: steps
  save_strategy: steps
  predict_with_generate: true
  generation_max_length: 256
  save_steps: 250
  eval_steps: 250
  logging_steps: 50
  load_best_model_at_end: true
  metric_for_best_model: eval_loss
  greater_is_better: false
  save_total_limit: 2
  seed: 42
  remove_unused_columns: false

